services:
  postgres:
    container_name: ms_pg_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: chahid
      POSTGRES_PASSWORD: chahid123
      POSTGRES_DB: example_db
      PG-DATA: /var/lib/postgresql/data
    volumes:
        - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      microservices_network:
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      microservices_network:
    restart: unless-stopped

  mongodb :
    container_name: ms_mongo
    image: mongo:latest
    volumes:
      - mongo:/data
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chahid
      - MONGO_INITDB_ROOT_PASSWORD=chahid123
    networks:
      microservices_network:
    restart: unless-stopped
  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chahid
      ME_CONFIG_MONGODB_ADMINPASSWORD: chahid123
      ME_CONFIG_MONGODB_SERVER: ms_mongo
    ports:
      - "8081:8081"
    networks:
      microservices_network:
    restart: unless-stopped

networks:
  microservices_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: